"""Command-line entry point:  python -m triage <command>

Commands (run in this order the first time):
  analyse        Clean the data, compute the headline numbers, draw team charts. No API.
  evaluate       Score the bot, the keyword baseline and Gemini on a fixed sample.
  label-sheet    Create outputs/hand_labels.csv for you to label by hand.
  categorise     Re-categorise tickets and draw the monthly-by-category chart.
  all            analyse + evaluate + categorise.

Use --engine rules to run everything without an API key.
"""
import argparse
import json

import pandas as pd
from dotenv import load_dotenv

from . import analysis, charts, config, evaluate
from .classify_rules import classify_messages
from .data import load_tickets
from .taxonomy import owner_group

OUT = config.OUTPUT_DIR


# ---------------------------------------------------------------- helpers
def _save_table(table: pd.DataFrame | pd.Series, name: str) -> None:
    table.to_csv(OUT / f"{name}.csv")


def _gemini(prompt_version: str, mode: str):
    from .classify_llm import GeminiClassifier  # imported lazily: rules mode needs no SDK
    return GeminiClassifier(prompt_version=prompt_version, mode=mode)


def _rules_labels(tickets: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame({"ticket_id": tickets["ticket_id"],
                         "category": classify_messages(tickets["customer_message"].tolist())})


def _cost_line(usage, n_tickets: int) -> str:
    """Cost of this run, and projected monthly cost at Vireo's stated volume."""
    if n_tickets == 0 or usage.calls == 0:
        return "No paid calls in this run (everything came from cache)."
    per_ticket_usd = usage.cost_usd() / n_tickets
    monthly_tickets = config.STATED_TICKETS_PER_WEEK * 52 / 12
    monthly_usd = per_ticket_usd * monthly_tickets
    return (f"{usage.calls} calls, {usage.input_tokens:,} input + {usage.output_tokens:,} "
            f"output tokens = ${usage.cost_usd():.4f} (~Rs {usage.cost_usd() * config.USD_TO_INR:.2f}) "
            f"for {n_tickets} tickets. At {config.STATED_TICKETS_PER_WEEK}/week "
            f"(~{monthly_tickets:,.0f}/month): ~${monthly_usd:.2f} "
            f"(~Rs {monthly_usd * config.USD_TO_INR:,.0f}) a month.")


# ---------------------------------------------------------------- commands
def cmd_analyse(args) -> None:
    tickets, log = load_tickets()
    agents = analysis.agents_table()
    share = analysis.team_share(tickets)
    workload = analysis.workload_per_agent(tickets, agents)
    headline = analysis.billing_to_logistics_cost(tickets)
    handoffs = analysis.cross_team_handoffs(tickets)
    scaled = analysis.scale_to_stated_volume(tickets, headline["total_inr_per_year"])
    impact = analysis.misroute_impact(tickets)
    by_quarter = analysis.misroute_rate_by_quarter(tickets)

    tag_monthly = analysis.monthly_counts(tickets, "assigned_group")
    work_monthly = analysis.monthly_counts(tickets, "resolving_group")
    for table, name in [(share, "team_share"), (workload, "workload_per_agent"),
                        (impact, "misroute_impact"), (tag_monthly, "monthly_by_bot_team"),
                        (work_monthly, "monthly_by_resolving_team"),
                        (analysis.monthly_counts(tickets, "category"), "monthly_by_bot_category"),
                        (by_quarter, "billing_misroute_rate_by_quarter")]:
        _save_table(table, name)
    charts.team_share_chart(share, OUT / "chart_team_share.png")
    charts.monthly_by_team_chart(tag_monthly, work_monthly, OUT / "chart_monthly_by_team.png")

    summary = f"""# Analysis summary (generated by `python -m triage analyse`)

## Data cleaning
{log}

## Share of tickets by team
{share.to_markdown()}

## Headline: delivery tickets routed to Billing (last 12 months)
{json.dumps(headline, indent=2, default=float)}

If the export is a sample of Vireo's ~650 tickets/week:
{json.dumps(scaled, indent=2)}

## All cross-team hand-offs (includes legitimate escalations)
{json.dumps(handoffs, indent=2)}

## What a misroute does to the customer (helpdesk era)
{impact.to_markdown()}

## Billing-queue misroute rate by quarter
{by_quarter.to_markdown()}

## Workload per agent (Jan-Jun 2026). Tier 2 is not comparable on volume (policy §6).
{workload.to_markdown()}
"""
    (OUT / "summary.md").write_text(summary)
    print(summary)
    print(f"Charts and tables written to {OUT}/")


def cmd_evaluate(args) -> None:
    tickets, _ = load_tickets()
    sample = evaluate.eval_sample(tickets, args.sample)
    predictions = {
        "Bot tag (today)": sample["assigned_group"],
        "Keyword baseline": _rules_labels(sample)["category"].map(owner_group),
    }
    label_sets = {"Bot tag (today)": sample[["ticket_id", "category"]],
                  "Keyword baseline": _rules_labels(sample)}
    cost_notes = []

    if args.engine == "gemini":
        for version in args.prompts:
            classifier = _gemini(version, mode="intake")
            labels = classifier.classify(sample)
            aligned = sample[["ticket_id"]].merge(labels, on="ticket_id", how="left")
            aligned["category"] = aligned["category"].fillna("Other")
            name = f"Gemini prompt {version}"
            predictions[name] = aligned["category"].map(owner_group)
            label_sets[name] = aligned
            cost_notes.append(f"- {name}: {_cost_line(classifier.usage, len(sample))} "
                              f"Invalid answers: {classifier.usage.invalid_answers}.")

    card = evaluate.scorecard(sample, predictions)
    best = list(predictions)[-1]
    confusion = evaluate.confusion(predictions[best], sample["resolving_group"])
    errors = sample.assign(predicted_group=predictions[best].values)
    errors = errors[errors["predicted_group"] != errors["resolving_group"]]
    errors[["ticket_id", "assigned_team", "resolving_team", "predicted_group",
            "customer_message", "agent_notes"]].to_csv(OUT / "evaluation_errors.csv", index=False)
    hand = evaluate.score_against_hand_labels(label_sets)

    report = f"""# Evaluation (generated by `python -m triage evaluate`)

Sample: {len(sample)} tickets, fixed random seed {evaluate.SAMPLE_SEED}.
Classifiers see ONLY the customer's opening message (what the bot sees at intake).
Truth = the team whose agent resolved the ticket.

## Scorecard
{card.to_markdown()}

## Confusion matrix for: {best}
{confusion.to_markdown()}

## Against reference labels (outputs/hand_labels.csv, first 100 tickets of the sample)
See the `comment` column of that file for who labelled them.
{hand.to_markdown() if hand is not None else "No labels yet. Run `python -m triage label-sheet`, fill in outputs/hand_labels.csv, then re-run."}

## Cost
{chr(10).join(cost_notes) or "Keyword baseline and bot tag cost nothing."}

Wrong answers for "{best}" are in outputs/evaluation_errors.csv.
"""
    (OUT / "evaluation.md").write_text(report)
    print(report)


def cmd_label_sheet(args) -> None:
    tickets, _ = load_tickets()
    evaluate.write_labelling_sheet(evaluate.eval_sample(tickets, args.sample), size=args.size)


def cmd_categorise(args) -> None:
    tickets, _ = load_tickets()
    if args.engine == "gemini":
        subset = tickets if args.all else evaluate.eval_sample(tickets, args.sample)
        classifier = _gemini(args.prompt, mode="full")
        labels = classifier.classify(subset)
        print(_cost_line(classifier.usage, len(subset)))
        model_name = f"Gemini ({args.prompt}, message + agent note)"
    else:
        subset = tickets
        labels = _rules_labels(tickets)
        model_name = "Keyword baseline"
    labelled = subset.merge(labels.rename(columns={"category": "new_category"}), on="ticket_id")
    labelled[["ticket_id", "month", "category", "new_category", "assigned_team",
              "resolving_team"]].to_csv(OUT / "ticket_categories.csv", index=False)
    by_tag = analysis.monthly_counts(labelled, "category")
    by_model = analysis.monthly_counts(labelled, "new_category")
    _save_table(by_model, "monthly_by_new_category")
    charts.monthly_by_category_chart(by_tag, by_model, model_name,
                                     OUT / "chart_monthly_by_category.png")
    note = "" if len(subset) == len(tickets) else f" (sample of {len(subset)}; use --all for every ticket)"
    print(f"Categorised {len(labelled)} tickets{note}. Chart: {OUT}/chart_monthly_by_category.png")


def main() -> None:
    load_dotenv()
    OUT.mkdir(exist_ok=True)
    parser = argparse.ArgumentParser(prog="python -m triage", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--engine", choices=["gemini", "rules"], default="gemini",
                        help="gemini (needs GEMINI_API_KEY) or rules (free keyword baseline)")
    parser.add_argument("--sample", type=int, default=300, help="evaluation sample size")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("analyse")
    ev = sub.add_parser("evaluate")
    ev.add_argument("--prompts", nargs="+", default=["v1", "v2"],
                    help="prompt versions in prompts/ to compare")
    ls = sub.add_parser("label-sheet")
    ls.add_argument("--size", type=int, default=100)
    cat = sub.add_parser("categorise")
    cat.add_argument("--prompt", default="v2")
    cat.add_argument("--all", action="store_true", help="every ticket, not just the sample")
    al = sub.add_parser("all")
    al.add_argument("--prompts", nargs="+", default=["v1", "v2"])
    al.add_argument("--prompt", default="v2")
    al.add_argument("--all", action="store_true")

    args = parser.parse_args()
    if args.command == "all":
        cmd_analyse(args)
        cmd_evaluate(args)
        cmd_categorise(args)
    else:
        {"analyse": cmd_analyse, "evaluate": cmd_evaluate, "label-sheet": cmd_label_sheet,
         "categorise": cmd_categorise}[args.command](args)
